##
##   █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗
##  ██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
##  ███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝
##  ██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝
##  ██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║
##  ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝

import = [
	"~/.config/alacritty/themes/catppuccin-mocha.toml"
]

live_config_reload = true

[cursor]
style = "block"

[font]
size = 17
normal.family = "JetBrainsMono Nerd Font"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"

[colors]
draw_bold_text_with_bright_colors = true

[selection]
save_to_clipboard = true

[scrolling]
history = 100000
multiplier = 6

[[keyboard.bindings]]
action = "Paste"
key = "R"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "W"
mods = "Alt"

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

opacity = 1
blur = true

[shell]
program = "/bin/zsh"
